"""
Hand-built mapping from OpenAlex's fine-grained `primary_topic` labels (as they
appear in data/processed/distinct_topics.csv) to a 3-level taxonomy:

    level1: Macro | Micro | Econometrics | Applied
    level2: a JEL-inspired subcategory within level1
    level3: the original OpenAlex topic label (already granular)

This is a judgment call, not an official classification (there's no free JEL-code
source cleanly attached to these journals) - review/edit freely.
"""

TOPIC_TAXONOMY = {
    "Auction Theory and Applications": ("Micro", "Auctions & Market Design"),
    "Economic theories and models": ("Micro", "General Economic Theory"),
    "Fiscal Policy and Economic Growth": ("Macro", "Fiscal Policy"),
    "Diverse Scientific and Economic Studies": ("Applied", "Other / Interdisciplinary"),
    "Labor market dynamics and wage inequality": ("Applied", "Labor Economics"),
    "Monetary Policy and Economic Impact": ("Macro", "Monetary Policy & Central Banking"),
    "Global trade and economics": ("Applied", "International Trade"),
    "Banking stability, regulation, efficiency": ("Macro", "Financial Markets & Stability"),
    "Experimental Behavioral Economics Studies": ("Micro", "Behavioral & Experimental Economics"),
    "Financial Literacy, Pension, Retirement Analysis": ("Applied", "Corporate & Household Finance"),
    "Consumer Market Behavior and Pricing": ("Micro", "Industrial Organization & Competition"),
    "Game Theory and Applications": ("Micro", "Game Theory & Mechanism Design"),
    "Gender, Labor, and Family Dynamics": ("Applied", "Labor Economics"),
    "Decision-Making and Behavioral Economics": ("Micro", "Behavioral & Experimental Economics"),
    "Culture, Economy, and Development Studies": ("Applied", "Development Economics"),
    "Global Financial Crisis and Policies": ("Macro", "Financial Markets & Stability"),
    "School Choice and Performance": ("Applied", "Education Economics"),
    "Corporate Finance and Governance": ("Applied", "Corporate & Household Finance"),
    "Human auditory perception and evaluation": ("Applied", "Other / Interdisciplinary"),
    "Financial Markets and Investment Strategies": ("Macro", "Financial Markets & Stability"),
    "Economic Growth and Productivity": ("Macro", "Business Cycles & Growth"),
    "Healthcare Policy and Management": ("Applied", "Health Economics"),
    "Housing Market and Economics": ("Macro", "Financial Markets & Stability"),
    "Advanced Causal Inference Techniques": ("Econometrics", "Causal Inference & Identification"),
    "Legal principles and applications": ("Applied", "Political Economy & Governance"),
    "Game Theory and Voting Systems": ("Micro", "Game Theory & Mechanism Design"),
    "Media Influence and Politics": ("Applied", "Political Economy & Governance"),
    "Employment and Welfare Studies": ("Applied", "Labor Economics"),
    "Law, Economics, and Judicial Systems": ("Applied", "Political Economy & Governance"),
    "Economic Theory and Policy": ("Micro", "General Economic Theory"),
    "Statistical Methods and Inference": ("Econometrics", "Statistical & Bayesian Methods"),
    "Intergenerational and Educational Inequality Studies": ("Applied", "Education Economics"),
    "Economic Theory and Institutions": ("Micro", "General Economic Theory"),
    "Regional Economics and Spatial Analysis": ("Applied", "Urban & Regional Economics"),
    "Economic and Environmental Valuation": ("Applied", "Environmental & Energy Economics"),
    "Firm Innovation and Growth": ("Micro", "Industrial Organization & Competition"),
    "Digital Platforms and Economics": ("Micro", "Industrial Organization & Competition"),
    "Electoral Systems and Political Participation": ("Applied", "Political Economy & Governance"),
    "Market Dynamics and Volatility": ("Macro", "Financial Markets & Stability"),
    "Urban, Neighborhood, and Segregation Studies": ("Applied", "Urban & Regional Economics"),
    "Taxation and Compliance Studies": ("Applied", "Public Finance & Taxation"),
    "Migration and Labor Dynamics": ("Applied", "Labor Economics"),
    "Poverty, Education, and Child Welfare": ("Applied", "Development Economics"),
    "Names, Identity, and Discrimination Research": ("Applied", "Labor Economics"),
    "Corporate Taxation and Avoidance": ("Applied", "Public Finance & Taxation"),
    "Global Health Care Issues": ("Applied", "Health Economics"),
    "Income, Poverty, and Inequality": ("Applied", "Development Economics"),
    "Microfinance and Financial Inclusion": ("Applied", "Development Economics"),
    "Fiscal Policies and Political Economy": ("Macro", "Fiscal Policy"),
    "Historical Economic and Social Studies": ("Applied", "Economic History"),
    "Economic and Technological Developments in Russia": ("Applied", "Development Economics"),
    "Merger and Competition Analysis": ("Micro", "Industrial Organization & Competition"),
    "Climate Change Policy and Economics": ("Applied", "Environmental & Energy Economics"),
    "Retirement, Disability, and Employment": ("Applied", "Labor Economics"),
    "Energy, Environment, and Transportation Policies": ("Applied", "Environmental & Energy Economics"),
    "Opinion Dynamics and Social Influence": ("Applied", "Other / Interdisciplinary"),
    "Early Childhood Education and Development": ("Applied", "Education Economics"),
    "Advanced Bandit Algorithms Research": ("Econometrics", "Machine Learning in Economics"),
    "Crime, Illicit Activities, and Governance": ("Applied", "Political Economy & Governance"),
    "Land Rights and Reforms": ("Applied", "Development Economics"),
    "Innovation Policy and R&D": ("Micro", "Industrial Organization & Competition"),
    "China's Socioeconomic Reforms and Governance": ("Applied", "Development Economics"),
    "Economics of Agriculture and Food Markets": ("Applied", "Development Economics"),
    "Complex Network Analysis Techniques": ("Econometrics", "Statistical & Bayesian Methods"),
    "Economic Policies and Impacts": ("Macro", "Business Cycles & Growth"),
    "Gender Politics and Representation": ("Applied", "Political Economy & Governance"),
    "Corruption and Economic Development": ("Applied", "Development Economics"),
    "Higher Education Research Studies": ("Applied", "Education Economics"),
    "Islamic Finance and Banking Studies": ("Applied", "Corporate & Household Finance"),
    "Corporate Insolvency and Governance": ("Applied", "Corporate & Household Finance"),
    "Agricultural risk and resilience": ("Applied", "Development Economics"),
    "Italy: Economic History and Contemporary Issues": ("Applied", "Economic History"),
    "Air Quality and Health Impacts": ("Applied", "Environmental & Energy Economics"),
    "Pharmaceutical Economics and Policy": ("Applied", "Health Economics"),
    "Insurance and Financial Risk Management": ("Macro", "Financial Markets & Stability"),
    "Supply Chain Resilience and Risk Management": ("Micro", "Industrial Organization & Competition"),
    "Credit Risk and Financial Regulations": ("Macro", "Financial Markets & Stability"),
    "Labor Movements and Unions": ("Applied", "Labor Economics"),
    "Opioid Use Disorder Treatment": ("Applied", "Health Economics"),
    "Transportation and Mobility Innovations": ("Applied", "Urban & Regional Economics"),
    "Intergenerational Family Dynamics and Caregiving": ("Applied", "Labor Economics"),
    "Populism, Right-Wing Movements": ("Applied", "Political Economy & Governance"),
    "Advanced Statistical Methods and Models": ("Econometrics", "Statistical & Bayesian Methods"),
    "Global Trade and Competitiveness": ("Applied", "International Trade"),
    "COVID-19 Pandemic Impacts": ("Applied", "Health Economics"),
    "German Economic Analysis & Policies": ("Macro", "Business Cycles & Growth"),
    "Intellectual Property and Patents": ("Micro", "Industrial Organization & Competition"),
    "Financial Risk and Volatility Modeling": ("Macro", "Financial Markets & Stability"),
    "Demographic Trends and Gender Preferences": ("Applied", "Labor Economics"),
    "Health Systems, Economic Evaluations, Quality of Life": ("Applied", "Health Economics"),
    "Regional Development and Policy": ("Applied", "Urban & Regional Economics"),
    "Migration, Ethnicity, and Economy": ("Applied", "Labor Economics"),
    "Spatial and Panel Data Analysis": ("Econometrics", "Time Series & Panel Data Methods"),
    "Education Systems and Policy": ("Applied", "Education Economics"),
    "Complex Systems and Time Series Analysis": ("Econometrics", "Time Series & Panel Data Methods"),
    "Education and experiences of immigrants and refugees": ("Applied", "Labor Economics"),
    "Organ Donation and Transplantation": ("Applied", "Health Economics"),
    "Criminal Justice and Corrections Analysis": ("Applied", "Political Economy & Governance"),
    "Defense, Military, and Policy Studies": ("Applied", "Political Economy & Governance"),
    "Local Government Finance and Decentralization": ("Applied", "Public Finance & Taxation"),
    "COVID-19 epidemiological studies": ("Applied", "Health Economics"),
    "Risk and Portfolio Optimization": ("Applied", "Corporate & Household Finance"),
    "Electric Power System Optimization": ("Applied", "Environmental & Energy Economics"),
    "Policing Practices and Perceptions": ("Applied", "Political Economy & Governance"),
    "Energy and Environment Impacts": ("Applied", "Environmental & Energy Economics"),
    "Political Influence and Corporate Strategies": ("Applied", "Political Economy & Governance"),
    "Migration, Refugees, and Integration": ("Applied", "Labor Economics"),
    "Birth, Development, and Health": ("Applied", "Health Economics"),
    "Economic, financial, and policy analysis": ("Macro", "Business Cycles & Growth"),
    "Evolutionary Game Theory and Cooperation": ("Micro", "Game Theory & Mechanism Design"),
    "Innovations in Educational Methods": ("Applied", "Education Economics"),
    "Global Energy and Sustainability Research": ("Applied", "Environmental & Energy Economics"),
    "Global trade, sustainability, and social impact": ("Applied", "International Trade"),
    "Global Maternal and Child Health": ("Applied", "Health Economics"),
    "Private Equity and Venture Capital": ("Applied", "Corporate & Household Finance"),
    "Healthcare Systems and Reforms": ("Applied", "Health Economics"),
    "Water resources management and optimization": ("Applied", "Environmental & Energy Economics"),
    "State Capitalism and Financial Governance": ("Macro", "Financial Markets & Stability"),
    "Sharing Economy and Platforms": ("Micro", "Industrial Organization & Competition"),
    "Sustainable Finance and Green Bonds": ("Applied", "Environmental & Energy Economics"),
    "Italian Fascism and Post-war Society": ("Applied", "Economic History"),
    "Race, History, and American Society": ("Applied", "Economic History"),
    "Machine Learning and Algorithms": ("Econometrics", "Machine Learning in Economics"),
    "Higher Education Governance and Development": ("Applied", "Education Economics"),
    "Blockchain Technology Applications and Security": ("Applied", "Corporate & Household Finance"),
    "Parental Involvement in Education": ("Applied", "Education Economics"),
    "Computational and Text Analysis Methods": ("Econometrics", "Machine Learning in Economics"),
    "Cognitive Abilities and Testing": ("Applied", "Other / Interdisciplinary"),
    "Forecasting Techniques and Applications": ("Econometrics", "Time Series & Panel Data Methods"),
    "Fire effects on ecosystems": ("Applied", "Environmental & Energy Economics"),
    "Gender Diversity and Inequality": ("Applied", "Labor Economics"),
    "Climate variability and models": ("Applied", "Environmental & Energy Economics"),
    "Economic Sanctions and International Relations": ("Applied", "International Trade"),
    "Bayesian Modeling and Causal Inference": ("Econometrics", "Causal Inference & Identification"),
    "Aviation Industry Analysis and Trends": ("Micro", "Industrial Organization & Competition"),
    "International Business and FDI": ("Applied", "International Trade"),
    "Diverse Perspectives in Modern Studies": ("Applied", "Other / Interdisciplinary"),
    "Health disparities and outcomes": ("Applied", "Health Economics"),
    "Social Policy and Reform Studies": ("Applied", "Political Economy & Governance"),
    "Advanced Queuing Theory Analysis": ("Econometrics", "Statistical & Bayesian Methods"),
    "Sustainable Development and Environmental Policy": ("Applied", "Environmental & Energy Economics"),
    "Urbanization and City Planning": ("Applied", "Urban & Regional Economics"),
    "Asian Industrial and Economic Development": ("Applied", "Development Economics"),
    "Risk Perception and Management": ("Micro", "Behavioral & Experimental Economics"),
    "Communication in Education and Healthcare": ("Applied", "Other / Interdisciplinary"),
    "Job Satisfaction and Organizational Behavior": ("Applied", "Labor Economics"),
    "Gender, Security, and Conflict": ("Applied", "Political Economy & Governance"),
    "Social Media and Politics": ("Applied", "Political Economy & Governance"),
    "Blind Source Separation Techniques": ("Econometrics", "Statistical & Bayesian Methods"),
    "Child Abuse and Trauma": ("Applied", "Other / Interdisciplinary"),
    "scientometrics and bibliometrics research": ("Applied", "Other / Interdisciplinary"),
    "Human Resource and Talent Management": ("Applied", "Labor Economics"),
    "Evaluation and Performance Assessment": ("Econometrics", "Statistical & Bayesian Methods"),
    "Youth Development and Social Support": ("Applied", "Other / Interdisciplinary"),
    "Gender Roles and Identity Studies": ("Applied", "Labor Economics"),
    "Stochastic Gradient Optimization Techniques": ("Econometrics", "Machine Learning in Economics"),
    "Vaccine Coverage and Hesitancy": ("Applied", "Health Economics"),
    "Child Welfare and Adoption": ("Applied", "Other / Interdisciplinary"),
    "Global Socioeconomic and Political Dynamics": ("Applied", "Development Economics"),
    "AI and HR Technologies": ("Applied", "Labor Economics"),
    "Educational Leadership and Practices": ("Applied", "Education Economics"),
    "Entrepreneurship Studies and Influences": ("Micro", "Industrial Organization & Competition"),
    "Political Philosophy and Ethics": ("Applied", "Political Economy & Governance"),
    "Psychosocial Factors Impacting Youth": ("Applied", "Other / Interdisciplinary"),
    "Ethics and Social Impacts of AI": ("Applied", "Other / Interdisciplinary"),
    "Academic and Historical Perspectives in Psychology": ("Applied", "Other / Interdisciplinary"),
    "International Science and Diplomacy": ("Applied", "Political Economy & Governance"),
    "Misinformation and Its Impacts": ("Applied", "Political Economy & Governance"),
    "Gambling Behavior and Treatments": ("Micro", "Behavioral & Experimental Economics"),
    "Dispute Resolution and Class Actions": ("Applied", "Political Economy & Governance"),
    "Gun Ownership and Violence Research": ("Applied", "Political Economy & Governance"),
    "Digital Economy and Work Transformation": ("Applied", "Labor Economics"),
    "Deception detection and forensic psychology": ("Applied", "Other / Interdisciplinary"),
    "International Development and Aid": ("Applied", "Development Economics"),
    "Social Capital and Networks": ("Applied", "Other / Interdisciplinary"),
    "Space Science and Extraterrestrial Life": ("Applied", "Other / Interdisciplinary"),
    "Pesticide and Herbicide Environmental Studies": ("Applied", "Environmental & Energy Economics"),
    "Diversity and Career in Medicine": ("Applied", "Health Economics"),
    "Occupational and Professional Licensing Regulation": ("Applied", "Labor Economics"),
    "Rangeland Management and Livestock Ecology": ("Applied", "Environmental & Energy Economics"),
    "Bayesian Methods and Mixture Models": ("Econometrics", "Statistical & Bayesian Methods"),
    "Face and Expression Recognition": ("Applied", "Other / Interdisciplinary"),
    "Community Health and Development": ("Applied", "Health Economics"),
    "Urban and Rural Development Challenges": ("Applied", "Urban & Regional Economics"),
    "Religion and Society Interactions": ("Applied", "Other / Interdisciplinary"),
    "Homelessness and Social Issues": ("Applied", "Other / Interdisciplinary"),
    "Global Cancer Incidence and Screening": ("Applied", "Health Economics"),
    "Work-Family Balance Challenges": ("Applied", "Labor Economics"),
    "Sleep and Work-Related Fatigue": ("Applied", "Labor Economics"),
    "Online Learning and Analytics": ("Applied", "Education Economics"),
    "Legal Education and Practice Innovations": ("Applied", "Political Economy & Governance"),
    "Psychology of Moral and Emotional Judgment": ("Applied", "Other / Interdisciplinary"),
    "Technology Adoption and User Behaviour": ("Micro", "Industrial Organization & Competition"),
    "Older Adults Driving Studies": ("Applied", "Other / Interdisciplinary"),
    "Religion, Society, and Development": ("Applied", "Development Economics"),
    "Health, Environment, Cognitive Aging": ("Applied", "Health Economics"),
    "South Asian Cinema and Culture": ("Applied", "Other / Interdisciplinary"),
    "Insurance, Mortality, Demography, Risk Management": ("Applied", "Corporate & Household Finance"),
    "Sociopolitical Dynamics in Russia": ("Applied", "Political Economy & Governance"),
    "Statistical Methods and Bayesian Inference": ("Econometrics", "Statistical & Bayesian Methods"),
    "Economic Growth and Development": ("Macro", "Business Cycles & Growth"),
    "Politics and Conflicts in Afghanistan, Pakistan, and Middle East": ("Applied", "Political Economy & Governance"),
    "Natural Resources and Economic Development": ("Applied", "Environmental & Energy Economics"),
    "Grit, Self-Efficacy, and Motivation": ("Applied", "Other / Interdisciplinary"),
    "Child and Adolescent Psychosocial and Emotional Development": ("Applied", "Other / Interdisciplinary"),
    "Technology and Education Systems": ("Applied", "Education Economics"),
    "Judicial and Constitutional Studies": ("Applied", "Political Economy & Governance"),
    "Neural Networks and Applications": ("Econometrics", "Machine Learning in Economics"),
    "Socioeconomic Development in MENA": ("Applied", "Development Economics"),
    "Terrorism, Counterterrorism, and Political Violence": ("Applied", "Political Economy & Governance"),
    "ICT Impact and Policies": ("Applied", "Development Economics"),
    "Contemporary Sociological Theory and Practice": ("Applied", "Other / Interdisciplinary"),
    "Public Procurement and Policy": ("Applied", "Public Finance & Taxation"),
    "Transportation Planning and Optimization": ("Applied", "Urban & Regional Economics"),
    "Regulation and Compliance Studies": ("Applied", "Political Economy & Governance"),
    "Indian Economic and Social Development": ("Applied", "Development Economics"),
    "Education Discipline and Inequality": ("Applied", "Education Economics"),
    "European Monetary and Fiscal Policies": ("Macro", "Monetary Policy & Central Banking"),
    "FinTech, Crowdfunding, Digital Finance": ("Applied", "Corporate & Household Finance"),
    "Academic Freedom and Politics": ("Applied", "Political Economy & Governance"),
    "Psychological and Educational Research Studies": ("Applied", "Other / Interdisciplinary"),
    "Optimism, Hope, and Well-being": ("Applied", "Other / Interdisciplinary"),
    "Energy, Environment, Economic Growth": ("Applied", "Environmental & Energy Economics"),
    "Financial Reporting and Valuation Research": ("Applied", "Corporate & Household Finance"),
    "Organizational Strategy and Culture": ("Applied", "Labor Economics"),
    "Academic integrity and plagiarism": ("Applied", "Other / Interdisciplinary"),
    "Coastal and Marine Management": ("Applied", "Environmental & Energy Economics"),
    "Urban Transport and Accessibility": ("Applied", "Urban & Regional Economics"),
    "Animal Ecology and Behavior Studies": ("Applied", "Other / Interdisciplinary"),
    "Flood Risk Assessment and Management": ("Applied", "Environmental & Energy Economics"),
    "Vietnamese History and Culture Studies": ("Applied", "Economic History"),
    "Climate Change Communication and Perception": ("Applied", "Environmental & Energy Economics"),
    "Impact of Technology on Adolescents": ("Applied", "Other / Interdisciplinary"),
    "Advanced Optimization Algorithms Research": ("Econometrics", "Machine Learning in Economics"),
    "Innovation and Socioeconomic Development": ("Applied", "Development Economics"),
    "Politics, Economics, and Education Policy": ("Applied", "Education Economics"),
    "Neural Networks and Reservoir Computing": ("Econometrics", "Machine Learning in Economics"),
    "Seed and Plant Biochemistry": ("Applied", "Other / Interdisciplinary"),
    "Housing, Finance, and Neoliberalism": ("Macro", "Financial Markets & Stability"),
    "Social and Cultural Dynamics": ("Applied", "Other / Interdisciplinary"),
    "Innovation and Knowledge Management": ("Micro", "Industrial Organization & Competition"),
    "Education Methods and Practices": ("Applied", "Education Economics"),
    "Sports Analytics and Performance": ("Applied", "Other / Interdisciplinary"),
    "Child and Adolescent Health": ("Applied", "Health Economics"),
    "Stochastic processes and financial applications": ("Applied", "Corporate & Household Finance"),
    "Information Retrieval and Search Behavior": ("Econometrics", "Machine Learning in Economics"),
    "Mental Health and Psychiatry": ("Applied", "Health Economics"),
    "Scheduling and Optimization Algorithms": ("Econometrics", "Machine Learning in Economics"),
    "Prenatal Screening and Diagnostics": ("Applied", "Health Economics"),
    "Air Traffic Management and Optimization": ("Applied", "Urban & Regional Economics"),
    "Family Dynamics and Relationships": ("Applied", "Labor Economics"),
    "Child Development and Digital Technology": ("Applied", "Education Economics"),
    "Food Security and Health in Diverse Populations": ("Applied", "Development Economics"),
    "Assisted Reproductive Technology and Twin Pregnancy": ("Applied", "Health Economics"),
    "Genetics, Bioinformatics, and Biomedical Research": ("Applied", "Other / Interdisciplinary"),
    "Cultural Differences and Values": ("Applied", "Other / Interdisciplinary"),
    "Consumer Retail Behavior Studies": ("Micro", "Industrial Organization & Competition"),
    "Behavioral Health and Interventions": ("Applied", "Health Economics"),
    "Auditing, Earnings Management, Governance": ("Applied", "Corporate & Household Finance"),
    "Economic and Technological Innovation": ("Micro", "Industrial Organization & Competition"),
    "Social Power and Status Dynamics": ("Applied", "Other / Interdisciplinary"),
    "Privacy-Preserving Technologies in Data": ("Econometrics", "Machine Learning in Economics"),
    "Markov Chains and Monte Carlo Methods": ("Econometrics", "Statistical & Bayesian Methods"),
    "Geriatric Care and Nursing Homes": ("Applied", "Health Economics"),
    "Innovation Diffusion and Forecasting": ("Econometrics", "Time Series & Panel Data Methods"),
    "Fuzzy Systems and Optimization": ("Econometrics", "Statistical & Bayesian Methods"),
    "Advanced Statistical Process Monitoring": ("Econometrics", "Statistical & Bayesian Methods"),
    "Probabilistic and Robust Engineering Design": ("Econometrics", "Statistical & Bayesian Methods"),
    "Mobile Crowdsensing and Crowdsourcing": ("Econometrics", "Machine Learning in Economics"),
}
